verbose: true
base_link: gripper_cam_optical_frame
models:
 - name: arm
   type: chain
   frame: chilitag1_link
 - name: camera
   type: camera2d
   frame: gripper_cam_optical_frame
free_params:
 - arm_joint_0
 - arm_joint_1
 - arm_joint_2
 - arm_joint_3
free_frames:
 - name: chilitag1_link
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
# - name: chilitag2_link
#   x: true
#   y: true
#   z: true
#   roll: true
#   pitch: true
#   yaw: true
# - name: chilitag3_link
#   x: true
#   y: true
#   z: true
#   roll: true
#   pitch: true
#   yaw: true
 - name: gripper_cam_optical_frame
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
error_blocks:
 - name: hand_eye
   type: camera2d_to_arm
   camera: camera
   arm: arm
# - name: restrict_camera
#   type: outrageous
#   param: head_camera_rgb_joint
#   joint_scale: 0.0
#   position_scale: 0.1
#   rotation_scale: 0.1
