verbose: true
base_link: arm_zoom_cam_optical_frame
models:
 - name: arm
   type: chain
   frame: base_link
 - name: camera
   type: camera2d
   frame: arm_zoom_cam_optical_frame
free_params:
 - arm_joint_0
 - arm_joint_1
 - arm_joint_2
 - sensor_head_pitch_joint
 - sensor_head_yaw_joint
free_frames:
 - name: chilitag4_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: chilitag5_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: chilitag7_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: arm_zoom_cam_optical_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
error_blocks:
 - name: hand_eye
   type: camera2d_to_arm
   camera: camera
   arm: arm
# - name: restrict_camera
#   type: outrageous
#   param: head_camera_rgb_joint
#   joint_scale: 0.0
#   position_scale: 0.1
#   rotation_scale: 0.1
