verbose: true
base_link: gripper_cam_optical_frame
models:
 - name: arm
   type: chain
   frame: chilitag1_link
 - name: camera
   type: camera2d
   frame: gripper_cam_optical_frame
free_params:
 - arm_joint_0
#free_frames:
# - name: base_chilitag_link
#   x: false
#   y: false
#   z: false
#   roll: false
#   pitch: false
#   yaw: falses
error_blocks:
 - name: hand_eye
   type: camera2d_to_arm
   camera: camera
   arm: arm
# - name: restrict_camera
#   type: outrageous
#   param: head_camera_rgb_joint
#   joint_scale: 0.0
#   position_scale: 0.1
#   rotation_scale: 0.1
