chains:
  - name: arm
    topic: /arm_control/arm_traj_controller/follow_joint_trajectory/goal
    joints:
     - arm_joint_0
     - arm_joint_1
     - arm_joint_2
     - arm_joint_3
    planning_group: arm #arm_group
duration: 2.0
features:
  chilitag_finder:
    type: robot_calibration/ChilitagFinder2D
    size: 0.05
    tag_ids: [0, 1]
    debug: true
    camera_sensor_name: camera
    chain_sensor_name: arm
