moveit:
  planning_group: arm_group
  joints:
   - arm_joint_0
   - arm_joint_1
   - arm_joint_2
   - sensor_head_pitch_joint
   - sensor_head_yaw_joint

features:
  chilitag_finder:
    type: robot_calibration/ChilitagFinder2D
    size: 0.05
    tag_ids: [0, 1]
    debug: true
    camera_sensor_name: camera
    chain_sensor_name: arm
